/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudalumnos;
import plantillapdfmain.PlantillaPdfMain;

import java.awt.Image;
import javax.swing.ImageIcon;

import static crudalumnos.AlumnoDao.cargarDatosEnTabla;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.util.Collections;
import plantillapdfmain.PlantillaPdfMain;
import static plantillapdfmain.PlantillaPdfMain.main;
/**
 *
 * @author Laboratorio
 */
public class CrudAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form CrudAlumnos
     */
 
    public CrudAlumnos() {
        initComponents();
        AlumnoDao.llenar();
        AlumnoDao.cargarDatosEnTabla(tblAlumno);
        //agrega el componente mouseListener y crea metodo para obtener datos de tabla
        tblAlumno.addMouseListener(new MouseAdapter(){
          public void mousePressed(MouseEvent Mouse_evt){  //creo el metodo custom mouse pressed e importo la libreria MouseEvent
           //creo un obj de JTable
            JTable table = (JTable) Mouse_evt.getSource();
            Point point = Mouse_evt.getPoint(); //Clase que representa la ubicacion coordenadas como entero
            int row = table.rowAtPoint(point); //almaceno el evento en una fila
            if(Mouse_evt.getClickCount() == 1){ //si detecta un click ....
               jTextFieldRut.setText(tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 0).toString()); //llena el jtextfield con el valor d la row y la columna 1 corrspondiente al nombre en la tabla
               jTextFieldNombre.setText(tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 1).toString());
               jTextFieldEdad.setText(tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 2).toString());
            }
              
          }   
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRut = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jButton1Agregar = new javax.swing.JButton();
        jButton2Buscar = new javax.swing.JButton();
        jButton3Eliminar = new javax.swing.JButton();
        jButton4Modificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("CRUD ALUMNOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 40));

        jLabel2.setText("Rut:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTextFieldRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRutActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jButton1Agregar.setText("Agregar Registro");
        jButton1Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        jButton2Buscar.setText("Buscar por RUT");
        jButton2Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));

        jButton3Eliminar.setText("Eliminar por RUT");
        jButton3Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, -1));

        jButton4Modificar.setText("Modificar por RUT");
        jButton4Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 130, -1));

        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(tblAlumno);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 450, 160));

        jButton1.setText("Crear informe pdf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 130, -1));

        jButton2.setText("Ver informe pdf");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setText("puede seleccionar un elemento de la tabla para operaciones CRUD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crudalumnos/ICONS/duoc.png"))); // NOI18N
        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRutActionPerformed

    public void limpiar(){
    
        jTextFieldRut.setText("");
        jTextFieldNombre.setText("");
        jTextFieldEdad.setText("");
    }
    
    public boolean validaJtextNull(){
        boolean estado = false;
        if (jTextFieldRut.getText().trim().length() == 0){
              JOptionPane.showMessageDialog(null,"campo rut debe contener datos");
              estado = true;
        }else if (jTextFieldNombre.getText().trim().length() == 0){
             JOptionPane.showMessageDialog(null,"campo nombre debe contener datos");
             estado = true;
        }else if (jTextFieldEdad.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"campo Edad debe contener datos");
            estado = true;
        }
        return estado;
    }
     
    
    
    private void jButton1AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AgregarActionPerformed
        // TODO add your handling code here:
        //definicion de variables
      
     try{
        
        if (validaJtextNull()== true){
           System.out.println("Campos vacios"); 
         }else{    validaJtextNull();  
          
          String rut = "";
          String nombre = "";
          Byte edad = 0;
        
        //lectura de datos
          rut=jTextFieldRut.getText();
          nombre=jTextFieldNombre.getText();
          edad=Byte.parseByte(jTextFieldEdad.getText());
        
          Alumno alumno = new Alumno(rut, nombre, edad);
        
          if (AlumnoDao.agregar(alumno) == true){
             JOptionPane.showMessageDialog(null, "Alumno ingresado exitosamente!!");
          }else{
             JOptionPane.showMessageDialog(null, "Datos de Alumno no agregados");

          }
          limpiar();
          AlumnoDao.cargarDatosEnTabla(tblAlumno);   
         }
       } catch(Exception e){
            System.out.println(e.getMessage());
      }  
        

    }//GEN-LAST:event_jButton1AgregarActionPerformed

    private void jButton4ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ModificarActionPerformed
        // TODO add your handling code here:
      try{
        
          if (validaJtextNull()== true){
             System.out.println("Campos vacios"); 
            }else{      
              String rut = "";
              rut=jTextFieldRut.getText();
        
              Alumno alumnoExistente = AlumnoDao.buscar(rut);
          
             if (alumnoExistente != null){
                String nuevoNombre = jTextFieldNombre.getText();
                byte nuevaEdad = Byte.parseByte(jTextFieldEdad.getText());
            
                Alumno nuevoAlumno = new Alumno(rut, nuevoNombre, nuevaEdad);
            
               if (AlumnoDao.modificar(rut, nuevoAlumno)){
                    JOptionPane.showMessageDialog(null, "Alumno modificado exitosamente!!");
                 }else{
                   JOptionPane.showMessageDialog(null, "error, nos e pudo modificar registro!");
                 }
                 }else{
                   JOptionPane.showMessageDialog(null, "No se encontro el Alumno");
                }
               limpiar();
               AlumnoDao.cargarDatosEnTabla(tblAlumno);
             }
            } catch(Exception e){
              System.out.println(e.getMessage());
              }  
          
    }//GEN-LAST:event_jButton4ModificarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jButton2BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2BuscarActionPerformed
        // TODO add your handling code here:
        
        
        String rut = "";
        rut=jTextFieldRut.getText();
        
        Alumno alumno = AlumnoDao.buscar(rut);
        
        if(alumno != null){
            jTextFieldNombre.setText(alumno.getNombre());
            jTextFieldEdad.setText(String.valueOf(alumno.getEdad()));
        }else{
           JOptionPane.showMessageDialog(null, "error rut no existe");
        } 
        
        
    }//GEN-LAST:event_jButton2BuscarActionPerformed

    private void jButton3EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EliminarActionPerformed
        // TODO add your handling code here:
        try{
         //if (validaJtextNull()== true){
          //   System.out.println("Campos vacios"); 
        // }else{
          String rut = "";
          rut=jTextFieldRut.getText();
        
          if(AlumnoDao.eliminar(rut)){
             JOptionPane.showMessageDialog(null, "registro eliminado exitosamente");
        }else{
           JOptionPane.showMessageDialog(null, "no se puede eliminar registro, rut no existe");
        } 
          limpiar();
          AlumnoDao.cargarDatosEnTabla(tblAlumno);
         //}
             
       
          //limpiar();
         
        }catch(Exception e){
          System.out.println(e.getMessage());
      }  
       
    }//GEN-LAST:event_jButton3EliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PlantillaPdfMain.creaplantilla();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PlantillaPdfMain.abrirPDF();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CrudAlumnos().setVisible(true);
               CrudAlumnos frame = new CrudAlumnos();
            // Centrar la ventana en la pantalla
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Agregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2Buscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3Eliminar;
    private javax.swing.JButton jButton4Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldRut;
    private javax.swing.JTable tblAlumno;
    // End of variables declaration//GEN-END:variables
}
